Ingredient.create!([
  {name: "potatoes", category: "Vegetables"},
  {name: "asparagus", category: "Vegetables"},
  {name: "tomatoes", category: "Vegetables"},
  {name: "broccoli", category: "Vegetables"},
  {name: "cauliflower", category: "Vegetables"},
  {name: "brussels sprouts", category: "Vegetables"},
  {name: "bok choy", category: "Vegetables"},
  {name: "onions", category: "Vegetables"},
  {name: "bell peppers", category: "Vegetables"},
  {name: "jalapeno peppers", category: "Vegetables"},
  {name: "lettuce", category: "Vegetables"},
  {name: "cabbage", category: "Vegetables"},
  {name: "endive", category: "Vegetables"},
  {name: "radicchio", category: "Vegetables"},
  {name: "green onions", category: "Vegetables"},
  {name: "chives", category: "Vegetables"},
  {name: "kale", category: "Vegetables"},
  {name: "swiss chard", category: "Vegetables"},
  {name: "mustard greens", category: "Vegetables"},
  {name: "garlic", category: "Vegetables"},
  {name: "beets", category: "Vegetables"},
  {name: "radishes", category: "Vegetables"},
  {name: "carrots", category: "Vegetables"},
  {name: "peas", category: "Vegetables"},
  {name: "cucumbers", category: "Vegetables"},
  {name: "zucchini", category: "Vegetables"},
  {name: "fava beans", category: "Vegetables"},
  {name: "shallots", category: "Vegetables"},
  {name: "turnips", category: "Vegetables"},
  {name: "rutabaga", category: "Vegetables"},
  {name: "summer squash", category: "Vegetables"},
  {name: "acorn squash", category: "Vegetables"},
  {name: "artichoke", category: "Vegetables"},
  {name: "avocado", category: "Vegetables"},
  {name: "parsnips", category: "Vegetables"},
  {name: "rhubarb", category: "Vegetables"},
  {name: "sauerkraut", category: "Vegetables"},
  {name: "kimchi", category: "Vegetables"},
  {name: "vegetable stock", category: "Vegetables"},
  {name: "okra", category: "Vegetables"},
  {name: "apples", category: "Fruit"},
  {name: "oranges", category: "Fruit"},
  {name: "pears", category: "Fruit"},
  {name: "grapes", category: "Fruit"},
  {name: "lemons", category: "Fruit"},
  {name: "limes", category: "Fruit"},
  {name: "kumquats", category: "Fruit"},
  {name: "raisins", category: "Fruit"},
  {name: "apricots", category: "Fruit"},
  {name: "peaches", category: "Fruit"},
  {name: "nectarines", category: "Fruit"},
  {name: "yuzu", category: "Fruit"},
  {name: "mangoes", category: "Fruit"},
  {name: "passion fruit", category: "Fruit"},
  {name: "star fruit", category: "Fruit"},
  {name: "durian", category: "Fruit"},
  {name: "guava", category: "Fruit"},
  {name: "bananas", category: "Fruit"},
  {name: "raspberries", category: "Fruit"},
  {name: "blueberries", category: "Fruit"},
  {name: "blackberries", category: "Fruit"},
  {name: "cherries", category: "Fruit"},
  {name: "kiwis", category: "Fruit"},
  {name: "plantains", category: "Fruit"},
  {name: "tangerines", category: "Fruit"},
  {name: "strawberries", category: "Fruit"},
  {name: "chicken wings", category: "Meat"},
  {name: "chicken legs", category: "Meat"},
  {name: "chicken breast", category: "Meat"},
  {name: "chicken thighs", category: "Meat"},
  {name: "whole chicken", category: "Meat"},
  {name: "steak", category: "Meat"},
  {name: "pork", category: "Meat"},
  {name: "pork chops", category: "Meat"},
  {name: "lamb", category: "Meat"},
  {name: "lamb shanks", category: "Meat"},
  {name: "tofu", category: "Vegetables"},
  {name: "cilantro", category: "Vegetables"},
  {name: "trout", category: "Meat"},
  {name: "bass", category: "Meat"},
  {name: "tuna", category: "Meat"},
  {name: "salmon", category: "Meat"},
  {name: "turkey", category: "Meat"},
  {name: "flounder", category: "Meat"},
  {name: "catfish", category: "Meat"},
  {name: "rabbit", category: "Meat"},
  {name: "duck", category: "Meat"},
  {name: "goose", category: "Meat"},
  {name: "ground beef", category: "Meat"},
  {name: "filet mignon", category: "Meat"},
  {name: "ribeye steaks", category: "Meat"},
  {name: "t-bone steaks", category: "Meat"},
  {name: "porterhouse steaks", category: "Meat"},
  {name: "pork ribs", category: "Meat"},
  {name: "pork shank", category: "Meat"},
  {name: "beef cheeks", category: "Meat"},
  {name: "turkey legs", category: "Meat"},
  {name: "turkey breast", category: "Meat"},
  {name: "bratwurst", category: "Meat"},
  {name: "hot dogs", category: "Meat"},
  {name: "keilbasa", category: "Meat"},
  {name: "bacon", category: "Meat"},
  {name: "prosciutto", category: "Meat"},
  {name: "ham", category: "Meat"},
  {name: "lamb sausage", category: "Meat"},
  {name: "pork sausage", category: "Meat"},
  {name: "pork belly", category: "Meat"},
  {name: "chicken stock", category: "Meat"},
  {name: "pork stock", category: "Meat"},
  {name: "fish stock", category: "Meat"},
  {name: "beef stock", category: "Meat"},
  {name: "milk", category: "Dairy"},
  {name: "heavy cream", category: "Dairy"},
  {name: "half and half", category: "Dairy"},
  {name: "cheddar cheese", category: "Dairy"},
  {name: "swiss cheese", category: "Dairy"},
  {name: "blue cheese", category: "Dairy"},
  {name: "gorgonzola cheese", category: "Dairy"},
  {name: "eggs", category: "Dairy"},
  {name: "goat cheese", category: "Dairy"},
  {name: "buttermilk", category: "Dairy"},
  {name: "baguette", category: "Grains"},
  {name: "whole wheat bread", category: "Grains"},
  {name: "white bread", category: "Grains"},
  {name: "macaroni", category: "Grains"},
  {name: "spaghetti", category: "Grains"},
  {name: "penne pasta", category: "Grains"},
  {name: "flour", category: "Grains"},
  {name: "brown rice", category: "Grains"},
  {name: "white rice", category: "Grains"},
  {name: "basmati rice", category: "Grains"},
  {name: "farro", category: "Grains"},
  {name: "barley", category: "Grains"},
  {name: "arborio rice", category: "Grains"},
  {name: "country bread", category: "Grains"},
  {name: "bow tie pasta", category: "Grains"},
  {name: "black beans", category: "Grains"},
  {name: "navy beans", category: "Grains"},
  {name: "quinoa", category: "Grains"},
  {name: "kidney beans", category: "Grains"},
  {name: "red lentils", category: "Grains"},
  {name: "yellow lentils", category: "Grains"},
  {name: "green lentils", category: "Grains"},
  {name: "yams", category: "Vegetables"},
  {name: "cayenne pepper", category: "Other"},
  {name: "curry powder", category: "Other"},
  {name: "bologna", category: "Meat"},
  {name: "kosher salt", category: "Other"},
  {name: "salt", category: "Other"},
  {name: "yogurt", category: "Dairy"},
  {name: "mozzarella cheese", category: "Dairy"},
  {name: "brown sugar", category: "Other"},
  {name: "sweet potatoes", category: "Vegetables"},
  {name: "sugar", category: "Other"},
  {name: "baking chocolate", category: "Other"},
  {name: "chicken feet", category: "Meat"},
  {name: "basil", category: "Other"},
  {name: "bay leaf", category: "Other"},
  {name: "cinnamon", category: "Other"},
  {name: "sardines", category: "Meat"},
  {name: "dill pickles", category: "Vegetables"},
  {name: "pineapple", category: "Fruit"},
  {name: "salami", category: "Meat"},
  {name: "pepperoni", category: "Meat"},
  {name: "lobster", category: "Meat"},
  {name: "crab", category: "Meat"},
  {name: "butter", category: "Dairy"},
  {name: "paprika", category: "Other"},
  {name: "venison", category: "Meat"}
])


User.create!(username: "Guest", password: "password")
